### ISSUE TITLE
COPR repository rather Fedora EPEL

### ISSUE THREAD

**Issue by robert-scheck** [dockingbay/centos-prosody#1]
May I ask you to use Fedora EPEL rather COPR? The COPR builds are meant to be nightly builds only, they might work, but they may eat the system. Regular updates in Fedora EPEL 5, 6 and 7 are stable working, tested releases of Prosody.

Btw, I am the package maintainer of Prosody in Fedora, EPEL and COPR.

**Comment by jistr** [comment]
EPEL was the first place where i went looking, only when i didn't find prosody in EPEL 7 i went looking for alternatives. I'll move this to EPEL then. (Not promising any time frame though. If you need this urgently, feel free to submit a pull request.)

**Comment by jistr** [comment]
Prosody only appeared in EPEL about 6 weeks ago, right? This repo is older, that's why i used something else.

**Comment by robert-scheck** [comment]
Prosody is in EPEL since 2015-04-24, the COPR repository exists since 2015-06-24.

**Comment by jistr** [comment]
Ah right, i used a different Prosody COPR at first (since January 2015) and then probably switched without checking EPEL. Anyway, thanks for bringing this up. It's on the backlog :)

**Comment by jistr** [comment]
Done in https://github.com/dockingbay/centos-prosody/commit/538b8bdc33dbaac1b92efa0886b55ed705ede910
